# Generated by Django 3.2.5 on 2021-08-14 15:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('user_id', models.IntegerField()),
                ('is_superuser', models.BooleanField(default=False)),
                ('username', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(default=None, max_length=255)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=datetime.datetime(2021, 8, 14, 18, 36, 16, 620750))),
                ('first_name', models.CharField(max_length=150)),
                ('balance', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='OutputApplication',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('amount', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ShopsAndSales',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('main_user', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('uncreated', models.DateTimeField()),
                ('price', models.FloatField()),
                ('not_main_user', models.IntegerField()),
                ('type', models.CharField(max_length=4)),
                ('ended', models.BooleanField()),
            ],
        ),
    ]
